// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxQowp7VQE_zXp9bFRO5rW-wrm8xKJKJs',
    appId: '1:741620867136:web:cc4f5198a59be593bb3fa5',
    messagingSenderId: '741620867136',
    projectId: 'feedbackabhyaz',
    authDomain: 'feedbackabhyaz.firebaseapp.com',
    storageBucket: 'feedbackabhyaz.appspot.com',
    measurementId: 'G-V7B8RTDR6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzEn1J2WRcHlvuSQKFLbsHfYTH75Nk2A0',
    appId: '1:741620867136:android:b42e6f5f86ee765cbb3fa5',
    messagingSenderId: '741620867136',
    projectId: 'feedbackabhyaz',
    storageBucket: 'feedbackabhyaz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpTLQW6FlQuHQIQlCjtu22pyWrVe4DzTs',
    appId: '1:741620867136:ios:55a4da9a35cfe3febb3fa5',
    messagingSenderId: '741620867136',
    projectId: 'feedbackabhyaz',
    storageBucket: 'feedbackabhyaz.appspot.com',
    iosBundleId: 'com.example.feedbackAbhyaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpTLQW6FlQuHQIQlCjtu22pyWrVe4DzTs',
    appId: '1:741620867136:ios:38cd99fefa9eade3bb3fa5',
    messagingSenderId: '741620867136',
    projectId: 'feedbackabhyaz',
    storageBucket: 'feedbackabhyaz.appspot.com',
    iosBundleId: 'com.example.feedbackAbhyaz.RunnerTests',
  );
}
